config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :clientes
  resources :servicos
  resources :ajudantes
  resources :usuarios, only:[:new, :create, :show, :edit, :update, :destroy]
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'servicos', to: 'servicos#index' #!! 
  
  root "sessions#new"
  #get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_one :endereco, :dependent => :destroy
    has_many :servicos, :dependent => :restrict_with_error
    belongs_to :usuario

    validates :nome, presence: true, length: {in:6..35}, format: {with: /\A[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+\z/ }
    validates_cpf_format_of :cpf
    validates :cpf, uniqueness: true
    validates :contato, presence: true, length: {in:8..15}, numericality: {only_integer:true}
    accepts_nested_attributes_for :endereco

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = current_usuario.clientes
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
    @cliente.build_endereco
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = current_usuario.clientes.build(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "Cliente foi criado com sucesso." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "Cliente foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    respond_to do |format|
    if @cliente.destroy
      format.html { redirect_to clientes_url, notice: "Cliente foi apagado com sucesso." }
      format.json { head :no_content }
    else
      format.html { redirect_to clientes_url, notice: "Cliente não pode ser apagado pois está em um ou mais Serviços" }
    end
  end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = current_usuario.clientes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :contato, {:endereco_attributes => [:id, :cidade, :bairro, :logradouro, :complemento]}, :usuario_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "erros") %> foram encontrados:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, "Nome do Cliente" %>
    <%= form.text_field :nome, placeholder:"Nome Completo" %>
  </div>

  <div class="field">
    <%= form.label :cpf, "CPF do Cliente" %>
    <%= form.text_field :cpf, placeholder:"xxx.xxx.xxx-xx", id:"cpf" %>
    <%= javascript_pack_tag 'cpf'%>
  </div>

  <div class="field">
    <%= form.label :contato, "Contato" %>
    <%= form.text_field :contato %>
  </div>

  <%= form.fields_for :endereco do |e| %>

    <div class="field">
      <%= e.label :cidade, "Cidade"%>
      <%= e.text_field :cidade %>
    </div>

    <div class="field">
      <%= e.label :bairro, "Bairro"%>
      <%= e.text_field :bairro %>
    </div>

    <div class="field">
      <%= e.label :lougradouro, "Logradouro" %>
      <%= e.text_field :logradouro %>
    </div>

    <div class="field">
      <%= e.label :complemento, "Complemento"%>
      <%= e.text_field :complemento %>
    </div>

  <% end %>

  <div class="actions">
    <%= form.submit id:"submit" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form', cliente: @cliente %>

<br><br>

<%= link_to 'Visualizar', @cliente %> |
<%= link_to 'Voltar', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Contato</th>
      <th>Cidade</th>
      <th>Bairro</th>
      <th>Logradouro</th>
      <th>Complemento</th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.contato %></td>
        <td><%= cliente.endereco.cidade %></td>
        <td><%= cliente.endereco.bairro %></td>
        <td><%= cliente.endereco.logradouro %></td>
        <td><%= cliente.endereco.complemento %></td>
        <td><%= link_to 'Visualizar', cliente, id:"s-#{cliente.nome}" %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente), id:"e-#{cliente.nome}" %></td>
        <td><%= link_to 'Apagar', cliente, method: :delete, id:"d-#{cliente.nome}", class:"delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path, id:"novo_cliente" %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render 'form', cliente: @cliente %>

<br><br>

<%= link_to 'Voltar', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @cliente.contato %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cliente.endereco.cidade %>
</p>
<p>
  <strong>Bairro:</strong>
  <%= @cliente.endereco.bairro %>
</p>
<p>
  <strong>Logradouro:</strong>
  <%= @cliente.endereco.logradouro %>
</p>
<p>
  <strong>Complemento:</strong>
  <%= @cliente.endereco.complemento %>
</p>

<br><br>

<%= link_to 'Editar Cliente', edit_cliente_path(@cliente) %> |
<%= link_to 'Voltar', clientes_path %>