config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :clientes
  resources :servicos
  resources :ajudantes
  resources :usuarios, only:[:new, :create, :show, :edit, :update, :destroy]
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'servicos', to: 'servicos#index' #!! 
  
  root "sessions#new"
  #get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/servico.rb
class Servico < ApplicationRecord
    belongs_to :usuario
    belongs_to :cliente
    belongs_to :ajudante ,optional: true
    belongs_to :material ,optional: true


    validates :tipoDoServico, presence: true, length: {in: 5..35}
    validates :descricao, presence: true, length: {in: 8..55}
    validates_date :data, on_or_after: -> (_lambda){Date.current}
    validates :valorDoServico, presence: true, numericality: {only_float:true, greater_than_or_equal_to: 1.0, less_than_or_equal_to: 1000000.0}

end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_servico, only: %i[ show edit update destroy ]

  # GET /servicos or /servicos.json
  def index
    @servicos = current_usuario.servicos
  end

  # GET /servicos/1 or /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
  end

  # GET /servicos/1/edit
  def edit
  end

  # POST /servicos or /servicos.json
  def create
    @servico = current_usuario.servicos.build(servico_params)

    respond_to do |format|
      if @servico.save
        format.html { redirect_to @servico, notice: "Serviço foi criado com sucesso." }
        format.json { render :show, status: :created, location: @servico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicos/1 or /servicos/1.json
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.html { redirect_to @servico, notice: "Serviço foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @servico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicos/1 or /servicos/1.json
  def destroy
    @servico.destroy
    respond_to do |format|
      format.html { redirect_to servicos_url, notice: "Serviço foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = current_usuario.servicos.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def servico_params
      params.require(:servico).permit(:tipoDoServico, :descricao, :data, :valorDoServico, :statusDePagamento, :cliente_id, :ajudante_id, :material_id)
    end
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/servicos/_form.html.erb
<%= form_with(model: servico) do |form| %>
  <% if servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servico.errors.count, "erros") %> foram encontrados:</h2>

      <ul>
        <% servico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, 'Cliente' %>
    <%= collection_select(:servico, :cliente_id, Cliente.where(usuario_id: current_usuario.id), :id, :nome, {:prompt => 'Selecione'}) %>
    <%= link_to 'Cadastrar novo cliente', new_cliente_path %>
  </div>

  <div class="field">
    <%= form.label :tipoDoServico, 'Tipo de Serviço Prestado' %>
    <%= form.text_field :tipoDoServico %>
  </div>

  <div class="field">
    <%= form.label :descricao, 'Descrição do Serviço' %>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label :ajudante, 'Ajudante' %>
    <%= form.collection_select(:ajudante_id, Ajudante.where(usuario_id: current_usuario.id), :id, :nome, {:prompt => 'Não possui'}) %>
    <%= link_to 'Cadastrar novo ajudante', new_ajudante_path %>
  </div>

  <div class="field">
    <%= form.label :material, 'Material' %>
    <%= form.collection_select(:material_id, Material.where(usuario_id: current_usuario.id), :id, :nome, {:prompt => 'Não possui'}) %>
    <%= link_to 'Cadastrar novo material', new_material_path %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.date_select(:data, :start_year => 2021, :end_year => 2023) %>
  </div>

  <div class="field">
    <%= form.label :valorDoServico, 'Valor do Serviço' %>
    <%= form.text_field :valorDoServico, placeholder: 'Somente números'%>
  </div>

  <div class="field">
    <%= form.label :statusDePagamento, 'Status de Pagamento' %>
    <%= form.check_box :statusDePagamento %>Pago
  </div>

  <div class="actions">
    <%= form.submit id:'submit' %>
  </div>
<% end %>

app/views/servicos/edit.html.erb
<h1>Editar Serviço</h1>

<%= render 'form', servico: @servico %>

<br><br>

<%= link_to 'Visualizar', @servico %> |
<%= link_to 'Voltar', servicos_path %>

app/views/servicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Serviços</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Serviço</th>
      <th>Descricao</th>
      <th>Ajudante</th>
      <th>Material</th>
      <th>Data</th>
      <th>Valor</th>
      <th>Status</th>
      
    </tr>
  </thead>

  <tbody>
    <% @servicos.each do |servico| %>
      <tr>
        <td><%= servico.cliente.nome %></td>
        <td><%= servico.tipoDoServico %></td>
        <td><%= servico.descricao %></td>
        <% if servico.ajudante_id != nil %>
          <td><%= servico.ajudante.nome %></td>
        <% else %>
          <td><%= 'Não possui' %></td>
        <% end %>
        <% if servico.material != nil %>
          <td><%= servico.material.nome %></td>
        <% else %>
          <td><%= 'Não possui' %></td>
        <% end %> 
        <td><%= servico.data %></td>
        <td><%= servico.valorDoServico %></td>
        <% if servico.statusDePagamento == true %>
          <td style="color:green"><%= "Pago" %></td>
        <% else %>
          <td style="color:red"><%= "Não Pago" %></td>
        <% end %>
        <td><%= link_to 'Visualizar', servico, id:"s-#{servico.cliente.nome + servico.tipoDoServico}" %></td>
        <td><%= link_to 'Editar', edit_servico_path(servico), id:"e-#{servico.cliente.nome + servico.tipoDoServico}" %></td>
        <td><%= link_to 'Apagar', servico, method: :delete, id:"d-#{servico.cliente.nome + servico.tipoDoServico}", class:"delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Serviço', new_servico_path, id:"novo_servico"%>

app/views/servicos/new.html.erb
<h1>Novo Serviço</h1>

<%= render 'form', servico: @servico %>

<br><br>

<%= link_to 'Voltar', servicos_path %>

app/views/servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @servico.cliente.nome %>
</p>

<p>
  <strong>Serviço:</strong>
  <%= @servico.tipoDoServico %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @servico.descricao %>
</p>

<p>
  <strong>Ajudante:</strong>
  <% if @servico.ajudante != nil %>
    <td><%= @servico.ajudante.nome %></td>
    <% else %>
    <td><%= 'Não possui' %></td>
  <% end %>
<p>

<p>
  <strong>Material:</strong>
  <% if @servico.material != nil %>
    <td><%= @servico.material.nome %></td>
    <% else %>
    <td><%= 'Não possui' %></td>
  <% end %>
<p>

<p>
  <strong>Data:</strong>
  <%= @servico.data %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @servico.valorDoServico %>
</p>

<p>
  <strong>Status:</strong>
  <% if @servico.statusDePagamento == true%>
    <%= "Pago" %>
  <% else %>
    <%= "Não Pago"%>
  <% end %>
</p>

<br><br>

<%= link_to 'Editar', edit_servico_path(@servico) %> |
<%= link_to 'Voltar', servicos_path %>