config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :clientes
  resources :servicos
  resources :ajudantes
  resources :usuarios, only:[:new, :create, :show, :edit, :update, :destroy]
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'servicos', to: 'servicos#index' #!! 
  
  root "sessions#new"
  #get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ajudante.rb
class Ajudante < ApplicationRecord
    has_many :servicos, :dependent => :nullify
    belongs_to :usuario

    validates :nome, presence: true, length: {in:6..35}, format: {with: /\A[a-zA-ZáàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+\z/ }
    validates_cpf_format_of :cpf
    validates :cpf, uniqueness: true
    validates :contato, presence: true, length: {in:8..15}, numericality: {only_integer:true}
    validates :precoMaoDeObra, presence: true, numericality: {only_float:true, greater_than_or_equal_to: 1.0, less_than_or_equal_to: 10000.0}
end

app/controllers/ajudantes_controller.rb
class AjudantesController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_ajudante, only: %i[ show edit update destroy ]

  # GET /ajudantes or /ajudantes.json
  def index
    @ajudantes = current_usuario.ajudantes
  end

  # GET /ajudantes/1 or /ajudantes/1.json
  def show
  end

  # GET /ajudantes/new
  def new
    @ajudante = Ajudante.new
  end

  # GET /ajudantes/1/edit
  def edit
  end

  # POST /ajudantes or /ajudantes.json
  def create
    @ajudante = current_usuario.ajudantes.build(ajudante_params)

    respond_to do |format|
      if @ajudante.save
        format.html { redirect_to @ajudante, notice: "Ajudante foi criado com sucesso." }
        format.json { render :show, status: :created, location: @ajudante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ajudante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ajudantes/1 or /ajudantes/1.json
  def update
    respond_to do |format|
      if @ajudante.update(ajudante_params)
        format.html { redirect_to @ajudante, notice: "Ajudante foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @ajudante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ajudante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ajudantes/1 or /ajudantes/1.json
  def destroy
    @ajudante.destroy
    respond_to do |format|
      format.html { redirect_to ajudantes_url, notice: "Ajudante foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ajudante
      @ajudante = current_usuario.ajudantes.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ajudante_params
      params.require(:ajudante).permit(:nome, :cpf, :contato, :precoMaoDeObra, :usuario_id)
    end
end

app/helpers/ajudantes_helper.rb
module AjudantesHelper
end

app/views/ajudantes/_form.html.erb
<%= form_with(model: ajudante) do |form| %>
  <% if ajudante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ajudante.errors.count, "erros") %> foram encontrados:</h2>

      <ul>
        <% ajudante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, "Nome do Ajundante" %>
    <%= form.text_field :nome, placeholder:"Nome Completo"%>
  </div>

  <div class="field">
    <%= form.label :cpf, "CPF" %>
    <%= form.text_field :cpf, placeholder:"xxx.xxx.xxx-xx",id:"cpf" %>
    <%= javascript_pack_tag 'cpf'%>
  </div>

  <div class="field">
    <%= form.label :contato, "Contato" %>
    <%= form.text_field :contato %>
  </div>

  <div class="field">
    <%= form.label :precoMaoDeObra, "Preço da mão de obra" %>
    <%= form.text_field :precoMaoDeObra %>
  </div>

  <div class="actions">
    <%= form.submit id:"submit" %>
  </div>
<% end %>

app/views/ajudantes/edit.html.erb
<h1>Editar Ajudante</h1>

<%= render 'form', ajudante: @ajudante %>

<br><br>

<%= link_to 'Visualizar', @ajudante %> |
<%= link_to 'Voltar', ajudantes_path %>

app/views/ajudantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ajudantes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>CPF</th>
      <th>Contato</th>
      <th>Preço da mão de obra</th>
    </tr>
  </thead>

  <tbody>
    <% @ajudantes.each do |ajudante| %>
      <tr>
        <td><%= ajudante.nome %></td>
        <td><%= ajudante.cpf %></td>
        <td><%= ajudante.contato %></td>
        <td><%= ajudante.precoMaoDeObra %></td>
        <td><%= link_to 'Visualizar', ajudante, id:"s-#{ajudante.nome}" %></td>
        <td><%= link_to 'Editar', edit_ajudante_path(ajudante), id:"e-#{ajudante.nome}" %></td>
        <td><%= link_to 'Apagar', ajudante, method: :delete, id:"d-#{ajudante.nome}", class:"delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>

<%= link_to 'Novo Ajudante', new_ajudante_path, id:"novo_ajudante" %>

app/views/ajudantes/new.html.erb
<h1>Novo Ajudante</h1>

<%= render 'form', ajudante: @ajudante %>

<br><br>

<%= link_to 'Voltar', ajudantes_path %>

app/views/ajudantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @ajudante.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @ajudante.cpf %>
</p>

<p>
  <strong>Contato:</strong>
  <%= @ajudante.contato %>
</p>

<p>
  <strong>Precomaodeobra:</strong>
  <%= @ajudante.precoMaoDeObra %>
</p>

<br><br>

<%= link_to 'Editar', edit_ajudante_path(@ajudante) %> |
<%= link_to 'Voltar', ajudantes_path %>