config/routes.rb
Rails.application.routes.draw do
  resources :materials
  resources :clientes
  resources :servicos
  resources :ajudantes
  resources :usuarios, only:[:new, :create, :show, :edit, :update, :destroy]
  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy'
  get 'servicos', to: 'servicos#index' #!! 
  
  root "sessions#new"
  #get 'sessions/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/material.rb
class Material < ApplicationRecord
    has_many :servico, :dependent => :nullify
    belongs_to :usuario

    validates :nome, presence: true, length: {in:3..35}, numericality: false
    validates :descricao, presence: true, length: {in:8..50}, numericality: false
    validates :valor, presence: true, numericality: {only_float:true, greater_than_or_equal_to: 1.0, less_than_or_equal_to: 100000.0}    
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_material, only: %i[ show edit update destroy ]

  # GET /materials or /materials.json
  def index
    @materials = current_usuario.materials
  end

  # GET /materials/1 or /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials or /materials.json
  def create
    @material = current_usuario.materials.build(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: "Material foi criado com sucesso." }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1 or /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: "Material foi atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1 or /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: "Material foi apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = current_usuario.materials.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def material_params
      params.require(:material).permit(:nome, :descricao, :valor)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_with(model: material) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "erros") %> foram encontrados:</h2>

      <ul>
        <% material.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, "Materias" %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descricao, "Descrição"%>
    <%= form.text_area :descricao %>
  </div>

  <div class="field">
    <%= form.label :valor, "Valor" %>
    <%= form.text_field :valor %>
  </div>

  <div class="actions">
    <%= form.submit id:"submit" %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editando Material</h1>

<%= render 'form', material: @material %>

<br><br>

<%= link_to 'Visualizar', @material %> |
<%= link_to 'Voltar', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Materiais</h1>

<table>
  <thead>
    <tr>
      <th>Nome do Material</th>
      <th>Descrição</th>
      <th>Valor</th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.nome %></td>
        <td><%= material.descricao %></td>
        <td><%= material.valor %></td>
        <td><%= link_to 'Visualizar', material, id:"s-#{material.nome}" %></td>
        <td><%= link_to 'Editar', edit_material_path(material), id:"e-#{material.nome}" %></td>
        <td><%= link_to 'Apagar', material, method: :delete, id:"d-#{material.nome}", class:"delete" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Material', new_material_path, id:"novo_material" %>

app/views/materials/new.html.erb
<h1>Novo Material</h1>

<%= render 'form', material: @material %>

<br><br>

<%= link_to 'Voltar', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @material.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @material.descricao %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @material.valor %>
</p>

<br><br>

<%= link_to 'Editar', edit_material_path(@material) %> |
<%= link_to 'Voltar', materials_path %>